#!/usr/bin/env bash
__ac_set() {
	COMPREPLY=( $(compgen -W "$*" -- ''${COMP_WORDS[COMP_CWORD]}) )
}

_scripts_ip() {
	COMPREPLY=()

	case "$COMP_CWORD" in
	1)
		__ac_set $(. scripts/ip && ip::list_servers)
		return;;
	esac
}

_scripts_ssh() {
	COMPREPLY=()

	case "$COMP_CWORD" in
	1)
		__ac_set $(. scripts/ip && ip::list_servers)
		return;;
	2)
		COMP_CWORD=$[ $COMP_CWORD - 1 ]
		COMP_WORDS=( ''${COMP_WORDS[@]:1} )
		COMP_WORDS[0]="ssh"
		COMP_LINE="''${COMP_WORDS[*]}"
		_ssh
		return;;
	esac
}

_scripts_package() {
	COMPREPLY=()

	case "$COMP_CWORD" in
	1)
		__ac_set list update
		return;;
	2)
		case "${COMP_WORDS[1]}" in
		update)
			__ac_set $(. scripts/pkg && pkg::list)
			return;;
		esac
	esac
}

complete -F _scripts_ip ./scripts/ip
complete -F _scripts_ssh ./scripts/ssh
complete -F _scripts_package ./scripts/pkg
