#!/usr/bin/env bash

main() {
	# Mask the SSH private key.
	./scripts/github/mask-file ./secrets/ssh/id_ed25519

	# Mask the AWS credentials.
	grep -oP '.* = \K.*' ./secrets/aws/credentials \
		| ./scripts/github/mask-lines

	# Mask all the IPs.
	tfstate '.resources[] | select(.type == "aws_instance") | .instances[].attributes.public_ip // empty' \
		| ./scripts/github/mask-lines
	tfstate '.resources[] | select(.type == "aws_instance") | .instances[].attributes.public_dns // empty' \
		| ./scripts/github/mask-lines

	# Mask this thing. I don't know what it is.
	tfstate '.resources[].instances[].private // empty' \
		| ./scripts/github/mask-lines
}

tfstate() {
	jq -r "$1" ./secrets/terraform.tfstate
}

main "$@"
