name: Decrypt git-crypt secrets

inputs:
  key:
    description: git-crypt exported key in base64
    required: true

runs:
  using: "composite"
  steps:
    - name: Decrypt git-crypt secrets
      id: git-crypt
      run: git-crypt unlock <(base64 -d <<< "$GIT_CRYPT_KEY")
      env:
        GIT_CRYPT_KEY: ${{ inputs.key }}
      shell: nix develop -c bash -e -o pipefail {0}
