name: Decrypt git-crypt secrets

inputs:
  key:
    description: git-crypt exported key in base64
    required: true

runs:
  using: "composite"
  steps:
    # Install git-crypt globally.
    # Otherwise, the git hooks won't work properly.
    - name: Install git-crypt
      run: |-
        nix profile install .#lib.nixpkgs.legacyPackages.x86_64-linux.git-crypt

    - name: Decrypt git-crypt secrets
      id: git-crypt
      run: git-crypt unlock <(base64 -d <<< "$GIT_CRYPT_KEY")
      env:
        GIT_CRYPT_KEY: ${{ inputs.key }}
