#!/usr/bin/env bash
set -e

main() {
	flags=()

	for arg in "$@"; do
		case "$arg" in
		-d|--decrypt)
			flags+=(-d)
			;;
		*)
			break
			;;
		esac
		shift
	done
	
	input="${1:-/dev/stdin}"
	output="${2:-/dev/stdout}"

	openssl aes-256-cbc -pbkdf2 -iter 131072 "${flags[@]}" \
		-in "$input" -out "$output" \
		-pass "file:./secrets/ssh/id_ed25519"
}

main "$@"
