#!/usr/bin/env bash
set -e

main() {
	for arg in "$@"; do
		case "$arg" in
		-d|--decrypt)
			decrypt=-d
			;;
		*)
			break
			;;
		esac
		shift
	done
	
	input="$1"
	output="$2"
	
	if [[ "$input" == "" ]]; then
		echo "Usage: $(basename "$0") [-d|--decrypt] input [output]"
		exit 1
	fi
	
	if [[ "$output" == "" ]]; then
		if [[ "$decrypt" == "1" ]]; then
			output="$input.dec"
		else
			output="$input.enc"
		fi
	fi

	openssl aes-256-cbc -pbkdf2 -iter 131072 $decrypt \
		-in "$input" -out "$output" \
		-pass "file:./secrets/ssh/id_ed25519"
}

main "$@"
