#!/usr/bin/env bash
set -e

main() {
	name="$1"
	if [[ $name == "" ]]; then
		echo "Usage: ./scripts/ssh <instance-name>"
		exit 1
	fi

	publicIP=$(jq -r --arg name $name \
		'.resources[] | select(.type == "aws_instance") | select(.name == $name) | .instances[0].attributes.public_ip // empty' \
		./secrets/terraform.tfstate)
	if [[ $publicIP == "" ]]; then
		echo "Instance $name not found" >&2
		exit 1
	fi

	echo -n "$publicIP"
}

main "$@"
