#!/usr/bin/env bash
. "$(dirname "$0")/lib/init"

main() {
	name="$1"
	if [[ $name == "" ]]; then
		echo "Usage: ./scripts/ip <instance-name>"
		exit 1
	fi

	if publicIP=$(ip::find "$name"); then
		echo "$publicIP"
		return
	fi

	if getent hosts "$name.$TAILNET_NAME.ts.net" > /dev/null; then
		echo "$name.$TAILNET_NAME.ts.net"
		return
	fi

	echo "Could not find IP for $name" >&2
	exit 1
}

# ip::find($1: instance_name?) -> public_ip?
ip::find() {
	local name
	name=$(jq -r \
		--arg name "$1" \
		'.resources[] | select(.type == "aws_instance") | select(.name == $name) | .instances[].attributes.public_ip // empty' \
		./secrets/terraform.tfstate)
	if [[ "$name" == "" ]]; then
		return 1
	fi

	echo "$name"
	return 0
}

# ip::list() -> (name + " " + public_ip)[]
ip::list() {
	jq -r '
		.resources[] |
			select(.type == "aws_instance") |
			"\(.name) \(.instances[].attributes.public_ip // empty)"' \
		./secrets/terraform.tfstate
}

# ip::list_servers() -> name[]
ip::list_servers() {
	while read -r name _; do
		echo "$name"
	done <<< "$(ip::list)"
}

ip::autocomplete() {
	local cur="${COMP_WORDS[COMP_CWORD]}"
	COMPREPLY=( $(compgen -W "$(tfstate::public_ip)" -- ${cur}) )
}

if lib::is_main; then
	main "$@"
fi
