#!/usr/bin/env bash
. "$(dirname "$0")/lib/init"

lib::include ip

# ssh::append_args($1: instance_name, $2: out_var)
ssh::append_args() {
	local target="$1"

	local user host
	if [[ "$target" == *"@"* ]]; then
		user="${target%%@*}"
		host="${target##*@}"
	else
		user="root"
		host="$target"
	fi

	if publicIP=$(ip::find "$host"); then
		host="$publicIP"
	else
		echo "No known IP for Tailscale name \"$host\", using it directly..." >&2
	fi

	declare -n outVar="$2"
	outVar+=( -o 'IdentitiesOnly=yes' -i './secrets/ssh/id_ed25519' "$user@$host" )
}

main() {
	local target="$1"

	sshArgs=()
	ssh::append_args "$target" sshArgs
	sshArgs+=( "${@:2}" )

	ssh "${sshArgs[@]}"
}

if lib::is_main; then
	main "$@"
fi
