#!/usr/bin/env bash
set -e

main() {
	if [[ "$1" == "" ]]; then
		echo "Usage: $0 <package> [commit]"
		exit 1
	fi

	local package="$1"
	local nivFlags=()

	if [[ "$2" != "" ]]; then
		if [[ "$2" == "v"* ]]; then
			nivFlags+=("-r" "$2")
		else
			nivFlags+=("-v" "$2")
		fi
	fi

	if [[ -d results ]]; then
		rm -r results
	fi
	mkdir -p results
	touch results/commit

	niv update "$package" "${nivFlags[@]}"

	(
		cd packages
		nix-update --version=skip "$package"
	)
}

main "$@"
