#!/usr/bin/env bash
set -e

main() {
	if [[ "$1" == "" ]]; then
		usage
	fi

	local package="$1"
	local nivFlags=()

	case "$2" in
	"v"*)
		nivFlags+=("-v" "$2");;
	[0-9a-f]*)
		nivFlags+=("-r" "$2");;
	"latest"|"")
		;;
	*)
		usage;;
	esac

	if [[ -d results ]]; then
		rm -r results
	fi
	mkdir -p results
	touch results/commit

	niv update "$package" "${nivFlags[@]}"

	(
		cd packages
		nix-update --version=skip "$package"
	)
}

usage() {
	echo "Usage: $0 <package> [commit]" >&2
	exit 1
}

main "$@"
