#!/usr/bin/env bash
. "$(dirname "$0")/lib/init"

lib::include ip

main() {
	local builderMachine="$1"
	local args=( "${@:2}" )

	if [[ "$builderMachine" == "" ]]; then
		echo "No builder machine specified, not using a builder" >&2
	else
		if ! addr=$(ip::find "$builderMachine"); then
			echo "Could not find IP for server '$builderMachine'" >&2
			exit 1
		fi

		system=$(nix-instantiate --eval --json "./servers/$builderMachine/" -A pkgs.system | jq -r)
		if [[ -z "$system" ]]; then
			echo "Could not determine system type for server '$builderMachine'" >&2
			exit 1
		fi

		echo "Using builder machine via SSH at $addr ($system)" >&2
		export NIX_CONFIG NIX_SSH_OPTS
		NIX_CONFIG="builders = ssh://$addr $system"
		NIX_SSH_OPTS="-i $(lib::root_path secrets/ssh/id_ed25519)"
	fi

	"${args[@]}"
}

if lib::is_main; then
	main "$@"
fi
